---
title: "Exericse3_larose"
author: "Sam Scott"
date: "2026-03-04"
output: html_document
---
bank <- read.csv('C:/Users/samsc/Desktop/ADS-502-Hands-On-Exercises/bank.csv', sep = ';')
bank

#11. Derive an index field and add it to the dataset

#How many records in the data set?
n <- dim(bank)[1]
bank$Index <- c(1:n)
head(bank)

#12. For the days_since_previous field, change the field value 999 to the appropriate code for
#missing values. (This dataset does not have this problem so it will be commented out!)

####bank_train$days_since_previous <- ifelse(test = bank_train$days_since_previous == 999, 
#### yes = NA, no = bank_train$days_since_previous)

#The ifelse() command checks the condition specified under test =, then assings the
#days_since_previous variable the value given after yes = if the test condition is true
# and assigns the days_since_previous variable the value given after no = if the test
#condition is false.(Larose, 2019)

#13. For the education field, reexpress the field values as the numeric values shown in Table 3.1

#Need this package installed
library(dplyr) 
unique(bank$education)
bank$education <- recode(bank$education, "unknown" = 0, "primary" = 1, "secondary" = 2, "tertiary" = 3)


#14. Standardize the field age. Print out a list of the first 10 records, including the 
#variables age and age_z.

bank$age_z <- scale(x = bank$age)

#15.Obtain a listing of all records that are outliers according to the outliers
#according to the field age_z. Print out a listing of the 10 largest age_z values.

age_outliers1 <- bank$age_z > 3
age_outliers2 <- bank$age_z < -3
outliers_age <- bank[age_outliers1 | age_outliers2, ]
outliers_age

#- minus sign sorts it in descending order. 
outliers_age_sort <- outliers_age[order(-outliers_age$age_z), ]

#16. For the job field, combine the jobs with less than 5% of the records into a field called other.
unique(bank$job)

#Look up how to do value_counts in R using table method
counts <- table(bank$job)
counts
length(counts)
sum(counts)

percentages <- counts/sum(counts) #vectorized operations so no need to 
rare_jobs <- names(percentages[percentages < 0.05])
rare_jobs

bank$job_recode <- ifelse(bank$job %in% rare_jobs, "other", bank$job)

table(bank$job_recode)

#18. For the variable month, change the field to 1-12, but keep the variable as categorical.
unique(bank$month)
bank$month <- recode(bank$month, "jan"= 1, "feb"= 2, "mar"= 3, "apr"= 4, 
"may"= 5, "jun"= 6, "jul"= 7, "aug"= 8, "sep"=9, "oct"= 10, "nov"= 11, "dec"= 12)


#19. Do the following for the duration field
#a. Standardize the field
#b. Identify how many outliers there are and identify the most extreme outlier.

bank$duration_z <- scale(x = bank$duration)

dur_outliers1 <- (bank$duration_z < -3)
dur_outliers2 <- (bank$duration_z > 3)
dur_outliers <- bank[dur_outliers1 | dur_outliers2, ]
dur_outliers

length(dur_outliers) 
#21

#sorts by duration_z but prints the id of those results
order(dur_outliers$duration_z)

bank_duration_z_sort <- dur_outliers[ order (-dur_outliers$duration_z),][1,21]

