---
title: "Exercise_Random_Forest_Larose"
author: "Sam Scott"
date: "2026-03-23"
output: html_document
---

#Data Science Using Python and R: Chapter 6 - Page 93: Questions #19 & 20

#Use both R and Python for these questions.

adult_train = read.csv('C:/Users/samsc/Desktop/ADS-502-Hands-On-Exercises/Data_Sets/adult_ch6_training.csv')
adult_test = read.csv('C:/Users/samsc/Desktop/ADS-502-Hands-On-Exercises/Data_Sets/adult_ch6_test.csv')

#19. Use random forests on training data set to predict income using marital status
#capital gains and losses

library(randomForest)

colnames(adult_train)[1] <- "maritalStatus"
colnames(adult_test)[1] <- "maritalStatus"

adult_train$Income <- factor(adult_train$Income)
adult_train$maritalStatus <- factor(adult_train$maritalStatus)

adult_test$Income <- factor(adult_test$Income)
adult_test$maritalStatus <- factor(adult_test$maritalStatus)

rf <- randomForest(formula = Income ~ maritalStatus + Cap_Gains_Losses, data = adult_train, ntree=100, type='classification')

rf$predicted


#20. Use random forests using the test data set that utilizes the same target
# and predictor variables. Does the test data result match the training data set?


rf_pred <- predict(rf, adult_test) #predicting for test data
rf_acc_test <- mean(rf_pred == adult_test$Income) 
rf_acc_train <- mean(rf$predicted == adult_train$Income) 


#The test data result matches the training data well with the test set slighty
#outperforming the training data. This means that the model generalizes overall
#really well. 
